apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: amqpqueues.hybridcloud.maibornwolff.de
spec:
  scope: Namespaced
  group: hybridcloud.maibornwolff.de
  names:
    kind: AMQPQueue
    plural: amqpqueues
    singular: amqpqueue
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                brokerRef:
                  type: object
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                  required:
                    - name
                allowedK8sNamespaces:
                  type: array
                  items:
                    type: string
                queue:
                  type: object
                  properties:
                    defaultTTLSeconds:
                      type: number
                    lockDurationSeconds:
                      type: number
                    enableDeadLettering:
                      type: boolean
                    maxDeliveryCount:
                      type: number
                credentialsSecret:
                  type: string
              required:
                - brokerRef
                - credentialsSecret
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              nullable: true
