apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: amqpbrokers.hybridcloud.maibornwolff.de
spec:
  scope: Namespaced
  group: hybridcloud.maibornwolff.de
  names:
    kind: AMQPBroker
    plural: amqpbrokers
    singular: amqpbroker
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                backend:
                  type: string
                allowedK8sNamespaces:
                  type: array
                  items:
                    type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              nullable: true
