apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: amqptopicsubscriptions.hybridcloud.maibornwolff.de
spec:
  scope: Namespaced
  group: hybridcloud.maibornwolff.de
  names:
    kind: AMQPTopicSubscription
    plural: amqptopicsubscriptions
    singular: amqptopicsubscription
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                topicRef:
                  type: object
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                  required:
                    - name
                subscription:
                  type: object
                  properties:
                    defaultTTLSeconds:
                      type: number
                    lockDurationSeconds:
                      type: number
                    enableDeadLettering:
                      type: boolean
                    maxDeliveryCount:
                      type: number
                credentialsSecret:
                  type: string
              required:
                - topicRef
                - credentialsSecret
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              nullable: true
